---
name: Molecule PostgresPro

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - centos8
          - debian10
          - debian11
          - ubuntu1804
          - ubuntu2004
          - ubuntu2204

    steps:
      - name: Set TERM environment variable
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: make bootstrap-dev

      - name: Run Molecule tests for PostgresPro
        run: make molecule-test-scenario
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          IMAGE_DISTRO: ${{ matrix.distro }}
          MOLECULE_SCENARIO: "postgrespro"
