---
name: scheduled PostgreSQL (Ubuntu 20.04)

on:
  schedule:
    - cron: "30 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set TERM environment variable
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: make bootstrap-dev

      - name: Run Molecule tests
        run: make molecule-test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          IMAGE_DISTRO: ubuntu2004
