---
apiVersion: v1
kind: ConfigMap
data:
  {{- range $key, $value := .Values.variables }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
metadata:
  name:  {{ include "sre-course-api.fullname" . }}